### ISSUE TITLE
Role may not be used to change `innodb_log_file_size` parameter of existing server installation

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-percona#24]
Related to #23

If the role is used to modify the value of `innodb_log_file_size` of an existing percona server installation, the database server service may fail to start due to an "InnoDB: Error: log file ./ib_logfile0 is of different size ...." error. 

When desired to change the value of `innodb_log_file_size` of an existing installation, the suggested procedure is as follows (ref. [here)](https://serverfault.com/questions/104014/innodb-error-log-file-ib-logfile0-is-of-different-size):

1. In the running MySQL instance, set `innodb_fast_shutdown=0` (it is 1 per default):
    ```
    mysql> set global innodb_fast_shutdown=0;
    Query OK, 0 rows affected (0.31 sec)

    mysql> show global variables like '%innodb_fast%';
    +----------------------+-------+
    | Variable_name        | Value |
    +----------------------+-------+
    | innodb_fast_shutdown | 0     |
    +----------------------+-------+
    1 row in set (0.00 sec)
    ```

2. Stop the database server service:
    ```
    # systemctl stop mysql.service
    ```

3. Make the configuration change to the log file size (e.g., set `innodb_log_file_size = 64M` in the `[mysqld]` section of `/etc/mysql/my.cnf`)

4. Delete or rename `ib_logfile0` and `ib_logfile1` in `/var/lib/mysql/`

5. Start the database server service
    ```
    # systemctl start mysql.service
    ```

**Comment by sevein** [comment]
Addressed by Miguel in https://github.com/artefactual-labs/ansible-percona/pull/44.
See task `"Abort when innodb_log_file_size changes"`.
